
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Address details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Address )
@SuperBuilder
@EqualsAndHashCode
public class Address
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Address identifier using special coding systems e.g. US CBP FIRMS code
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_addressCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement addressCode;
    /**
     * UN/LOCODE city code (5 letter) or IATA city code (3 letter)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_cityCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement cityCode;
    /**
     * Country details. Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_country)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement country;
    /**
     * Postal / ZIP code
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_postalCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement postalCode;
    /**
     * Region/ State / Department. Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_regionCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement regionCode;
    /**
     * Post Office box number / code
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_postOfficeBox)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String postOfficeBox;
    /**
     * Street address including street name, street number, building number, apartment etc
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_streetAddressLines)
    protected Set<String> streetAddressLines;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Address {"+ name)+"<")+ id)+">")+"}");
    }

    public void setAddressCode(CodeListElement addressCode) {
        this.addressCode = addressCode;
    }

    public CodeListElement getAddressCode() {
        return addressCode;
    }

    public void setCityCode(CodeListElement cityCode) {
        this.cityCode = cityCode;
    }

    public CodeListElement getCityCode() {
        return cityCode;
    }

    public void setCountry(CodeListElement country) {
        this.country = country;
    }

    public CodeListElement getCountry() {
        return country;
    }

    public void setPostalCode(CodeListElement postalCode) {
        this.postalCode = postalCode;
    }

    public CodeListElement getPostalCode() {
        return postalCode;
    }

    public void setRegionCode(CodeListElement regionCode) {
        this.regionCode = regionCode;
    }

    public CodeListElement getRegionCode() {
        return regionCode;
    }

    public void setPostOfficeBox(String postOfficeBox) {
        this.postOfficeBox = postOfficeBox;
    }

    public String getPostOfficeBox() {
        return postOfficeBox;
    }

    public void setStreetAddressLines(Set<String> streetAddressLines) {
        this.streetAddressLines = streetAddressLines;
    }

    public Set<String> getStreetAddressLines() {
        return streetAddressLines;
    }

}
