
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Adjustments in the context of CASS records
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Adjustments )
@SuperBuilder
@EqualsAndHashCode
public class Adjustments
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Number of the adjustment
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_correctionNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer correctionNumber;
    /**
     * Serial Number of the correction
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_correctionSerialNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String correctionSerialNumber;
    /**
     * A free text for user to include a reason for correction
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_reasonsForAdjustments)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String reasonsForAdjustments;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Adjustments {"+ name)+"<")+ id)+">")+"}");
    }

    public void setCorrectionNumber(Integer correctionNumber) {
        this.correctionNumber = correctionNumber;
    }

    public Integer getCorrectionNumber() {
        return correctionNumber;
    }

    public void setCorrectionSerialNumber(String correctionSerialNumber) {
        this.correctionSerialNumber = correctionSerialNumber;
    }

    public String getCorrectionSerialNumber() {
        return correctionSerialNumber;
    }

    public void setReasonsForAdjustments(String reasonsForAdjustments) {
        this.reasonsForAdjustments = reasonsForAdjustments;
    }

    public String getReasonsForAdjustments() {
        return reasonsForAdjustments;
    }

}
