
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Simplified shipment object that is to be used only for the distribution scope where only a subset of data is known priori to operational phase.
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_BookingShipment )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class BookingShipment
    extends LogisticsObject
{

    /**
     * Expected commodity of the shipment as per Commodity Code list. Either this or expected HS code required
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_expectedCommodity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CommodityCode expectedCommodity;
    /**
     * Expected commodity of the shipment as per HS code (at least 6 digits). Either this or expectedCommodityCode required
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_expectedHScode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement expectedHScode;
    /**
     * Reference to the BookingOptionRequest the information of the LogisticsObject is detailling
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forBookingOptionRequest)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingOptionRequest forBookingOptionRequest;
    /**
     * Reference to the Piece groups of the shipment
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_pieceGroups)
    protected Set<PieceGroup> pieceGroups;
    /**
     * Three-letter special handling code (SPH)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_specialHandlingCodes)
    protected Set<SpecialHandlingCode> specialHandlingCodes;
    /**
     * Temperature instructions if a specific range
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_temperatureInstructions)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected TemperatureInstructions temperatureInstructions;
    /**
     * Indication if the shipment is a consolidation
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_consolidationIndicator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean consolidationIndicator;
    /**
     * Special service requests
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_specialServiceRequests)
    protected Set<String> specialServiceRequests;
    /**
     * Strings to provide free text handling instructions such as SSR and OSI
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_textualHandlingInstructions)
    protected Set<String> textualHandlingInstructions;

    public void setExpectedCommodity(CommodityCode expectedCommodity) {
        this.expectedCommodity = expectedCommodity;
    }

    public CommodityCode getExpectedCommodity() {
        return expectedCommodity;
    }

    public void setExpectedHScode(CodeListElement expectedHScode) {
        this.expectedHScode = expectedHScode;
    }

    public CodeListElement getExpectedHScode() {
        return expectedHScode;
    }

    public void setForBookingOptionRequest(BookingOptionRequest forBookingOptionRequest) {
        this.forBookingOptionRequest = forBookingOptionRequest;
    }

    public BookingOptionRequest getForBookingOptionRequest() {
        return forBookingOptionRequest;
    }

    public void setPieceGroups(Set<PieceGroup> pieceGroups) {
        this.pieceGroups = pieceGroups;
    }

    public Set<PieceGroup> getPieceGroups() {
        return pieceGroups;
    }

    public void setSpecialHandlingCodes(Set<SpecialHandlingCode> specialHandlingCodes) {
        this.specialHandlingCodes = specialHandlingCodes;
    }

    public Set<SpecialHandlingCode> getSpecialHandlingCodes() {
        return specialHandlingCodes;
    }

    public void setTemperatureInstructions(TemperatureInstructions temperatureInstructions) {
        this.temperatureInstructions = temperatureInstructions;
    }

    public TemperatureInstructions getTemperatureInstructions() {
        return temperatureInstructions;
    }

    public void setConsolidationIndicator(Boolean consolidationIndicator) {
        this.consolidationIndicator = consolidationIndicator;
    }

    public Boolean getConsolidationIndicator() {
        return consolidationIndicator;
    }

    public void setSpecialServiceRequests(Set<String> specialServiceRequests) {
        this.specialServiceRequests = specialServiceRequests;
    }

    public Set<String> getSpecialServiceRequests() {
        return specialServiceRequests;
    }

    public void setTextualHandlingInstructions(Set<String> textualHandlingInstructions) {
        this.textualHandlingInstructions = textualHandlingInstructions;
    }

    public Set<String> getTextualHandlingInstructions() {
        return textualHandlingInstructions;
    }

}
