
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.time.OffsetDateTime;
import java.util.Set;


/**
 * CheckTemplate is the body of a check, holding links to multiple Question LOs and is provided by the party in charge of the template that is used
 * 
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_CheckTemplate )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class CheckTemplate
    extends LogisticsObject
{

    /**
     * Information about other Parties involved depending on the context of use
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_involvedParties)
    protected Set<Party> involvedParties;
    /**
     * Reference to an ExternalReference holding a legacy templats outside of ONE Record, such as a photo or pdf of a checksheet
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_legacyTemplate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected ExternalReference legacyTemplate;
    /**
     * References to all Questions that are part of this template
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_questions)
    protected Set<Question> questions;
    /**
     * Reference to the Check the template was used in
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_usedInCheck)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Check usedInCheck;
    /**
     * DateTime on which the CheckTemplate was released
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_date)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime date;
    /**
     * Human-understandable name of object depending on the context
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_name)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String name;
    /**
     * Purpose of the template
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_templatePurpose)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String templatePurpose;
    /**
     * Version of the template
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_version)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String version;

    public void setInvolvedParties(Set<Party> involvedParties) {
        this.involvedParties = involvedParties;
    }

    public Set<Party> getInvolvedParties() {
        return involvedParties;
    }

    public void setLegacyTemplate(ExternalReference legacyTemplate) {
        this.legacyTemplate = legacyTemplate;
    }

    public ExternalReference getLegacyTemplate() {
        return legacyTemplate;
    }

    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

    public Set<Question> getQuestions() {
        return questions;
    }

    public void setUsedInCheck(Check usedInCheck) {
        this.usedInCheck = usedInCheck;
    }

    public Check getUsedInCheck() {
        return usedInCheck;
    }

    public void setDate(OffsetDateTime date) {
        this.date = date;
    }

    public OffsetDateTime getDate() {
        return date;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setTemplatePurpose(String templatePurpose) {
        this.templatePurpose = templatePurpose;
    }

    public String getTemplatePurpose() {
        return templatePurpose;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getVersion() {
        return version;
    }

}
