
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;


/**
 * Action to describe a check
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Check )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
public class Check
    extends LogisticsAction    
{

    /**
     * Reference to the result of the Check
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checkTotalResult)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CheckTotalResult checkTotalResult;
    /**
     * Reference to the checked Object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checkedObject)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected LogisticsObject checkedObject;
    /**
     * Reference to the Actor performing the Check
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checker)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Actor checker;
    /**
     * Reference to the Template used in the Check
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_usedTemplate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CheckTemplate usedTemplate;

    public void setCheckTotalResult(CheckTotalResult checkTotalResult) {
        this.checkTotalResult = checkTotalResult;
    }

    public CheckTotalResult getCheckTotalResult() {
        return checkTotalResult;
    }

    public void setCheckedObject(LogisticsObject checkedObject) {
        this.checkedObject = checkedObject;
    }

    public LogisticsObject getCheckedObject() {
        return checkedObject;
    }

    public void setChecker(Actor checker) {
        this.checker = checker;
    }

    public Actor getChecker() {
        return checker;
    }

    public void setUsedTemplate(CheckTemplate usedTemplate) {
        this.usedTemplate = usedTemplate;
    }

    public CheckTemplate getUsedTemplate() {
        return usedTemplate;
    }

}
