
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;


/**
 * CO2 Calculation
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_CO2Emissions )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class CO2Emissions
    extends LogisticsObject
{

    /**
     * CO2 emissions calculated
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_calculatedEmissions)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value calculatedEmissions;
    /**
     * Reference to the TransportMovement or TransportLegs the CO2Emissions have been calculated for
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_calculationFor)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected LogisticsObject calculationFor;
    /**
     * Name of the CO2 calculation method
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_methodName)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String methodName;
    /**
     * Version used for the calculation
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_methodVersion)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String methodVersion;

    public void setCalculatedEmissions(Value calculatedEmissions) {
        this.calculatedEmissions = calculatedEmissions;
    }

    public Value getCalculatedEmissions() {
        return calculatedEmissions;
    }

    public void setCalculationFor(LogisticsObject calculationFor) {
        this.calculationFor = calculationFor;
    }

    public LogisticsObject getCalculationFor() {
        return calculationFor;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public String getMethodName() {
        return methodName;
    }

    public void setMethodVersion(String methodVersion) {
        this.methodVersion = methodVersion;
    }

    public String getMethodVersion() {
        return methodVersion;
    }

}
