
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;


/**
 * Company details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Company )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Company
    extends Organization
    implements Serializable
{

    /**
     * IATA accredited cargo agent 7 digit number
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_iataCargoAgentCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String iataCargoAgentCode;
    /**
     * IATA CASS cargo agent 4 digit branch number / location identifier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_iataCargoAgentLocationIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String iataCargoAgentLocationIdentifier;

    public void setIataCargoAgentCode(String iataCargoAgentCode) {
        this.iataCargoAgentCode = iataCargoAgentCode;
    }

    public String getIataCargoAgentCode() {
        return iataCargoAgentCode;
    }

    public void setIataCargoAgentLocationIdentifier(String iataCargoAgentLocationIdentifier) {
        this.iataCargoAgentLocationIdentifier = iataCargoAgentLocationIdentifier;
    }

    public String getIataCargoAgentLocationIdentifier() {
        return iataCargoAgentLocationIdentifier;
    }

}
