
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Action to describe build-up or break-down of LoadingUnits
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Composing )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Composing
    extends LogisticsAction
    implements Serializable
{

    /**
     * References to the Materials being built-up or broken-down
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_composedMaterials)
    protected Set<LoadingMaterial> composedMaterials;
    /**
     * References to the Pieces being built-up or broken-down
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_composedPieces)
    protected Set<Piece> composedPieces;
    /**
     * Enum stating whether the CompositionAction describes build-up or break-down
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_compositionType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CompositionType compositionType;
    /**
     * Reference to the LoadingUnit composed in the Unit Composition or referenced in Composing actions
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_loadingUnit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected LoadingUnit loadingUnit;

    public void setComposedMaterials(Set<LoadingMaterial> composedMaterials) {
        this.composedMaterials = composedMaterials;
    }

    public Set<LoadingMaterial> getComposedMaterials() {
        return composedMaterials;
    }

    public void setComposedPieces(Set<Piece> composedPieces) {
        this.composedPieces = composedPieces;
    }

    public Set<Piece> getComposedPieces() {
        return composedPieces;
    }

    public void setCompositionType(CompositionType compositionType) {
        this.compositionType = compositionType;
    }

    public CompositionType getCompositionType() {
        return compositionType;
    }

    public void setLoadingUnit(LoadingUnit loadingUnit) {
        this.loadingUnit = loadingUnit;
    }

    public LoadingUnit getLoadingUnit() {
        return loadingUnit;
    }

}
