
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Embedded object to transmit currencies
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_CurrencyValue )
@SuperBuilder
@EqualsAndHashCode
public class CurrencyValue
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Information about the currency used in a CurrencyValue. Create an instance of CurrencyCode based on ISO 4217
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_currencyUnit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CurrencyCode currencyUnit;
    /**
     * Numerical value
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_numericalValue)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double numericalValue;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("CurrencyValue {"+ name)+"<")+ id)+">")+"}");
    }

    public void setCurrencyUnit(CurrencyCode currencyUnit) {
        this.currencyUnit = currencyUnit;
    }

    public CurrencyCode getCurrencyUnit() {
        return currencyUnit;
    }

    public void setNumericalValue(Double numericalValue) {
        this.numericalValue = numericalValue;
    }

    public Double getNumericalValue() {
        return numericalValue;
    }

}
