
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.EqualsAndHashCode.Exclude;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Dimension details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Dimensions )
@SuperBuilder
@EqualsAndHashCode
@NoArgsConstructor
public class Dimensions
    implements Serializable
{

    @Id(generated = true)
    @Exclude
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    @Exclude
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Height
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_height)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value height;
    /**
     * Length
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_length)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value length;
    /**
     * Volume
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_volume)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value volume;
    /**
     * Width
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_width)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value width;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Dimensions {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHeight(Value height) {
        this.height = height;
    }

    public Value getHeight() {
        return height;
    }

    public void setLength(Value length) {
        this.length = length;
    }

    public Value getLength() {
        return length;
    }

    public void setVolume(Value volume) {
        this.volume = volume;
    }

    public Value getVolume() {
        return volume;
    }

    public void setWidth(Value width) {
        this.width = width;
    }

    public Value getWidth() {
        return width;
    }

}
