
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Insurance details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Insurance )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Insurance
    extends LogisticsObject
{

    /**
     * Party covering the insurance 
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_coveringOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Organization coveringOrganization;
    /**
     * Insured amount - amount covered by the insurance policy
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_insuredAmount)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CurrencyValue insuredAmount;
    /**
     * Reference to the shipments insured
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_insuredShipments)
    protected Set<Shipment> insuredShipments;

    public void setCoveringOrganization(Organization coveringOrganization) {
        this.coveringOrganization = coveringOrganization;
    }

    public Organization getCoveringOrganization() {
        return coveringOrganization;
    }

    public void setInsuredAmount(CurrencyValue insuredAmount) {
        this.insuredAmount = insuredAmount;
    }

    public CurrencyValue getInsuredAmount() {
        return insuredAmount;
    }

    public void setInsuredShipments(Set<Shipment> insuredShipments) {
        this.insuredShipments = insuredShipments;
    }

    public Set<Shipment> getInsuredShipments() {
        return insuredShipments;
    }

}
