
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Set;


/**
 * Item details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Item )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Item
    extends PhysicalLogisticsObject
    implements Serializable
{

    /**
     * Dimensions details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_dimensions)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Dimensions dimensions;
    /**
     * Reference to the Piece this Item or Piece is contained in
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_inPiece)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Piece inPiece;
    /**
     * Quantity of the item when applicable, with associated units of measure
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_itemQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value itemQuantity;
    /**
     * Reference to the Product describing the Item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ofProduct)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Product ofProduct;
    /**
     * Details about any other identifier, depending on the context of use
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherIdentifiers)
    protected Set<OtherIdentifier> otherIdentifiers;
    /**
     * Production country details. Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_productionCountry)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement productionCountry;
    /**
     * Item target country. Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_targetCountry)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement targetCountry;
    /**
     * Product price per unit in the base
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_unitPrice)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CurrencyValue unitPrice;
    /**
     * Weight of the item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_weight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value weight;
    /**
     * Production batch number / reference
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_batchNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String batchNumber;
    /**
     * Product expiry date - e.g. for perishables goods or goods with programmed obsolescence
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_expiryDate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime expiryDate;
    /**
     * Production lot number / reference
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_lotNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String lotNumber;
    /**
     * Production date
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_productionDate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime productionDate;
    /**
     * Product quantity for unit price - e.g. 12 (eggs for one USD 1)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_quantityForUnitPrice)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double quantityForUnitPrice;

    public void setDimensions(Dimensions dimensions) {
        this.dimensions = dimensions;
    }

    public Dimensions getDimensions() {
        return dimensions;
    }

    public void setInPiece(Piece inPiece) {
        this.inPiece = inPiece;
    }

    public Piece getInPiece() {
        return inPiece;
    }

    public void setItemQuantity(Value itemQuantity) {
        this.itemQuantity = itemQuantity;
    }

    public Value getItemQuantity() {
        return itemQuantity;
    }

    public void setOfProduct(Product ofProduct) {
        this.ofProduct = ofProduct;
    }

    public Product getOfProduct() {
        return ofProduct;
    }

    public void setOtherIdentifiers(Set<OtherIdentifier> otherIdentifiers) {
        this.otherIdentifiers = otherIdentifiers;
    }

    public Set<OtherIdentifier> getOtherIdentifiers() {
        return otherIdentifiers;
    }

    public void setProductionCountry(CodeListElement productionCountry) {
        this.productionCountry = productionCountry;
    }

    public CodeListElement getProductionCountry() {
        return productionCountry;
    }

    public void setTargetCountry(CodeListElement targetCountry) {
        this.targetCountry = targetCountry;
    }

    public CodeListElement getTargetCountry() {
        return targetCountry;
    }

    public void setUnitPrice(CurrencyValue unitPrice) {
        this.unitPrice = unitPrice;
    }

    public CurrencyValue getUnitPrice() {
        return unitPrice;
    }

    public void setWeight(Value weight) {
        this.weight = weight;
    }

    public Value getWeight() {
        return weight;
    }

    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public void setExpiryDate(OffsetDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    public OffsetDateTime getExpiryDate() {
        return expiryDate;
    }

    public void setLotNumber(String lotNumber) {
        this.lotNumber = lotNumber;
    }

    public String getLotNumber() {
        return lotNumber;
    }

    public void setProductionDate(OffsetDateTime productionDate) {
        this.productionDate = productionDate;
    }

    public OffsetDateTime getProductionDate() {
        return productionDate;
    }

    public void setQuantityForUnitPrice(Double quantityForUnitPrice) {
        this.quantityForUnitPrice = quantityForUnitPrice;
    }

    public Double getQuantityForUnitPrice() {
        return quantityForUnitPrice;
    }

}
