
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;


/**
 * Common loading unit/container details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LoadingUnit )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class LoadingUnit
    extends PhysicalLogisticsObject
    implements Serializable
{

    @OWLObjectProperty(iri = Vocabulary.s_p_inUnitComposition)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected UnitComposition inUnitComposition;
    /**
     * Tare weight of the empty ULD
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_tareWeight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value tareWeight;
    /**
     * Remarks or Supplement Information
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_remarks)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String remarks;

    public void setInUnitComposition(UnitComposition inUnitComposition) {
        this.inUnitComposition = inUnitComposition;
    }

    public UnitComposition getInUnitComposition() {
        return inUnitComposition;
    }

    public void setTareWeight(Value tareWeight) {
        this.tareWeight = tareWeight;
    }

    public Value getTareWeight() {
        return tareWeight;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getRemarks() {
        return remarks;
    }

}
