
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Superclass: LogisticsService is a sequence of Activities provided by one Party to another
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsService )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
public class LogisticsService
    extends LogisticsObject
{

    /**
     * Information about the Activities that are part of the Service and their sequence
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_activitySequences)
    protected Set<ActivitySequence> activitySequences;
    /**
     * Information about contactDetails
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_contactDetails)
    protected Set<ContactDetail> contactDetails;
    /**
     * References to Actors (Person, NonHumanActor) acting as contacts
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_contactPersons)
    protected Set<Actor> contactPersons;

    public void setActivitySequences(Set<ActivitySequence> activitySequences) {
        this.activitySequences = activitySequences;
    }

    public Set<ActivitySequence> getActivitySequences() {
        return activitySequences;
    }

    public void setContactDetails(Set<ContactDetail> contactDetails) {
        this.contactDetails = contactDetails;
    }

    public Set<ContactDetail> getContactDetails() {
        return contactDetails;
    }

    public void setContactPersons(Set<Actor> contactPersons) {
        this.contactPersons = contactPersons;
    }

    public Set<Actor> getContactPersons() {
        return contactPersons;
    }

}
