
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.EqualsAndHashCode.Exclude;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Logistics Object parent class, containing all common properties for logistics objects.
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsObject )
@SuperBuilder
@EqualsAndHashCode
@NoArgsConstructor
public class LogisticsObject
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * References to the CheckActions performed on the object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checks)
    protected Set<Check> checks;
    /**
     * Events object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_events)
    @Exclude
    protected Set<LogisticsEvent> events;
    /**
     * References to all associated ExternalReferences
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_externalReferences)
    protected Set<ExternalReference> externalReferences;
    /**
     * Indicator whether a logistics object is a skeleton object
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_skeletonIndicator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean skeletonIndicator;

    protected Integer latestRevision;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return this.getClass().getSimpleName() + "<" + this.getId() + ">";
    }

    public void setChecks(Set<Check> checks) {
        this.checks = checks;
    }

    public Set<Check> getChecks() {
        return checks;
    }

    public void setEvents(Set<LogisticsEvent> events) {
        this.events = events;
    }

    public Set<LogisticsEvent> getEvents() {
        return events;
    }

    public void setExternalReferences(Set<ExternalReference> externalReferences) {
        this.externalReferences = externalReferences;
    }

    public Set<ExternalReference> getExternalReferences() {
        return externalReferences;
    }

    public void setSkeletonIndicator(Boolean skeletonIndicator) {
        this.skeletonIndicator = skeletonIndicator;
    }

    public Boolean getSkeletonIndicator() {
        return skeletonIndicator;
    }

    public void setLatestRevision(Integer latestRevision) {
        this.latestRevision = latestRevision;
    }

    public Integer getLatestRevision() {
        return latestRevision;        
    }

}
