
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;


/**
 * Superclass: LogisticsAgents describe acting entities in the logistics supply chain such as persons and organizations
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsAgent )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
public class LogisticsAgent
    extends LogisticsObject
{


}
