
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Packaging details 
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PackagingType )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class PackagingType
    extends LogisticsObject
{

    /**
     * Piece on which the Packaging type is applicable
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_appliedOnPieces)
    protected Set<Piece> appliedOnPieces;
    /**
     * Packaging type identifier as per UNECE Rec 21 Annex V and VI e.g. 1A - Drum, steel - Packaging material code. Identifies the Logistic Unit package type. UN Recommendation on Transport of Dangerous Goods, Model Regulations 
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_typeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement typeCode;
    /**
     * Natural language description if required
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_description)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String description;

    public void setAppliedOnPieces(Set<Piece> appliedOnPieces) {
        this.appliedOnPieces = appliedOnPieces;
    }

    public Set<Piece> getAppliedOnPieces() {
        return appliedOnPieces;
    }

    public void setTypeCode(CodeListElement typeCode) {
        this.typeCode = typeCode;
    }

    public CodeListElement getTypeCode() {
        return typeCode;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

}
