
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Superclass: PhysicalLogisticObjects represent the digital twin of an object in the logistics suppy chain that physically exist
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PhysicalLogisticsObject )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
public class PhysicalLogisticsObject
    extends LogisticsObject
{

    /**
     * References to all connected IotDevices
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_attachedIotDevices)
    protected Set<IotDevice> attachedIotDevices;
    /**
     * References to the Actions the object is involved in
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_involvedInActions)
    protected Set<LogisticsAction> involvedInActions;

    public void setAttachedIotDevices(Set<IotDevice> attachedIotDevices) {
        this.attachedIotDevices = attachedIotDevices;
    }

    public Set<IotDevice> getAttachedIotDevices() {
        return attachedIotDevices;
    }

    public void setInvolvedInActions(Set<LogisticsAction> involvedInActions) {
        this.involvedInActions = involvedInActions;
    }

    public Set<LogisticsAction> getInvolvedInActions() {
        return involvedInActions;
    }

}
