
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Set;


/**
 * LiveAnimals subclass of Piece
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PieceLiveAnimals )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class PieceLiveAnimals
    extends Piece
    implements Serializable
{

    /**
     * Reference to the permits associated with the Live Animals
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_associatedEpermit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected EpermitConsignment associatedEpermit;
    /**
     * Country of last re-export (box 12a). Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_exportTradeCountry)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement exportTradeCountry;
    /**
     * Appendix number of the convention (I, II or III) (box 1)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_goodsTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected GoodsTypeCode goodsTypeCode;
    /**
     * Appendix number of the convention (I, II or III) (box 1)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_goodsTypeExtensionCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected GoodsTypeExtensionCode goodsTypeExtensionCode;
    /**
     * Document type code of origin reference permit or re-export reference Certificate (box 12/12a)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_originReferencePermitTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement originReferencePermitTypeCode;
    /**
     * country of origin (box 12). Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_originTradeCountry)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement originTradeCountry;
    /**
     * Description of specimens, CITES type code (box 9)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_specimenTypeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement specimenTypeCode;
    /**
     * Defined in Resolution Conf. 13.6 and is required for pre-Convention specimens (box 12b)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_acquisitionDateTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime acquisitionDateTime;
    /**
     * total number of specimens exported in the current calendar year and the current annuela quota for the species concerned (box 11a)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_annualQuotaQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer annualQuotaQuantity;
    /**
     * Operations code ID. Refers to the number of the registered captive-breeding or artifical propagation operation (box 12b)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_categoryCode)
    protected Set<String> categoryCode;
    /**
     * Issuing date for Origin reference permit or re-export reference Certificate (box 12)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_originReferencePermitDateTime)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime originReferencePermitDateTime;
    /**
     * identifier of Origin reference permit or re-export reference Certificate (box 12/12a)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_originReferencePermitId)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String originReferencePermitId;
    /**
     * Quantity including units (box 11)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_quantityAnimals)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer quantityAnimals;
    /**
     * Species common name (box 8)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_speciesCommonName)
    protected Set<String> speciesCommonName;
    /**
     * Species scientific name (box 7)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_speciesScientificName)
    protected Set<String> speciesScientificName;
    /**
     * Description of specimens, including age and sex if LA (box 9)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_specimenDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String specimenDescription;

    public void setAssociatedEpermit(EpermitConsignment associatedEpermit) {
        this.associatedEpermit = associatedEpermit;
    }

    public EpermitConsignment getAssociatedEpermit() {
        return associatedEpermit;
    }

    public void setExportTradeCountry(CodeListElement exportTradeCountry) {
        this.exportTradeCountry = exportTradeCountry;
    }

    public CodeListElement getExportTradeCountry() {
        return exportTradeCountry;
    }

    public void setGoodsTypeCode(GoodsTypeCode goodsTypeCode) {
        this.goodsTypeCode = goodsTypeCode;
    }

    public GoodsTypeCode getGoodsTypeCode() {
        return goodsTypeCode;
    }

    public void setGoodsTypeExtensionCode(GoodsTypeExtensionCode goodsTypeExtensionCode) {
        this.goodsTypeExtensionCode = goodsTypeExtensionCode;
    }

    public GoodsTypeExtensionCode getGoodsTypeExtensionCode() {
        return goodsTypeExtensionCode;
    }

    public void setOriginReferencePermitTypeCode(CodeListElement originReferencePermitTypeCode) {
        this.originReferencePermitTypeCode = originReferencePermitTypeCode;
    }

    public CodeListElement getOriginReferencePermitTypeCode() {
        return originReferencePermitTypeCode;
    }

    public void setOriginTradeCountry(CodeListElement originTradeCountry) {
        this.originTradeCountry = originTradeCountry;
    }

    public CodeListElement getOriginTradeCountry() {
        return originTradeCountry;
    }

    public void setSpecimenTypeCode(CodeListElement specimenTypeCode) {
        this.specimenTypeCode = specimenTypeCode;
    }

    public CodeListElement getSpecimenTypeCode() {
        return specimenTypeCode;
    }

    public void setAcquisitionDateTime(OffsetDateTime acquisitionDateTime) {
        this.acquisitionDateTime = acquisitionDateTime;
    }

    public OffsetDateTime getAcquisitionDateTime() {
        return acquisitionDateTime;
    }

    public void setAnnualQuotaQuantity(Integer annualQuotaQuantity) {
        this.annualQuotaQuantity = annualQuotaQuantity;
    }

    public Integer getAnnualQuotaQuantity() {
        return annualQuotaQuantity;
    }

    public void setCategoryCode(Set<String> categoryCode) {
        this.categoryCode = categoryCode;
    }

    public Set<String> getCategoryCode() {
        return categoryCode;
    }

    public void setOriginReferencePermitDateTime(OffsetDateTime originReferencePermitDateTime) {
        this.originReferencePermitDateTime = originReferencePermitDateTime;
    }

    public OffsetDateTime getOriginReferencePermitDateTime() {
        return originReferencePermitDateTime;
    }

    public void setOriginReferencePermitId(String originReferencePermitId) {
        this.originReferencePermitId = originReferencePermitId;
    }

    public String getOriginReferencePermitId() {
        return originReferencePermitId;
    }

    public void setQuantityAnimals(Integer quantityAnimals) {
        this.quantityAnimals = quantityAnimals;
    }

    public Integer getQuantityAnimals() {
        return quantityAnimals;
    }

    public void setSpeciesCommonName(Set<String> speciesCommonName) {
        this.speciesCommonName = speciesCommonName;
    }

    public Set<String> getSpeciesCommonName() {
        return speciesCommonName;
    }

    public void setSpeciesScientificName(Set<String> speciesScientificName) {
        this.speciesScientificName = speciesScientificName;
    }

    public Set<String> getSpeciesScientificName() {
        return speciesScientificName;
    }

    public void setSpecimenDescription(String specimenDescription) {
        this.specimenDescription = specimenDescription;
    }

    public String getSpecimenDescription() {
        return specimenDescription;
    }

}
