
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * PieceGroup details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PieceGroup )
@SuperBuilder
@EqualsAndHashCode
public class PieceGroup
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Weight of dry ice
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_dryIceWeight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value dryIceWeight;
    /**
     * Total gross weight of the piece group
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_pieceGroupGrossWeight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value pieceGroupGrossWeight;
    /**
     * Number of pieces in the piece group
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_pieceGroupCount)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer pieceGroupCount;
    /**
     * Identifier of the piece group, increasing integers
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_pieceGroupId)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer pieceGroupId;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("PieceGroup {"+ name)+"<")+ id)+">")+"}");
    }

    public void setDryIceWeight(Value dryIceWeight) {
        this.dryIceWeight = dryIceWeight;
    }

    public Value getDryIceWeight() {
        return dryIceWeight;
    }

    public void setPieceGroupGrossWeight(Value pieceGroupGrossWeight) {
        this.pieceGroupGrossWeight = pieceGroupGrossWeight;
    }

    public Value getPieceGroupGrossWeight() {
        return pieceGroupGrossWeight;
    }

    public void setPieceGroupCount(Integer pieceGroupCount) {
        this.pieceGroupCount = pieceGroupCount;
    }

    public Integer getPieceGroupCount() {
        return pieceGroupCount;
    }

    public void setPieceGroupId(Integer pieceGroupId) {
        this.pieceGroupId = pieceGroupId;
    }

    public Integer getPieceGroupId() {
        return pieceGroupId;
    }

}
