
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Price associated to the offer/booking
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Price )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Price
    extends LogisticsObject
{

    /**
     * Charge code, refer to CargoXML Code List 1.1
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_chargeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected ChargeCode chargeCode;
    /**
     * Reference to the BookingOption the LogisticsObject is detailling
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forBookingOption)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingOption forBookingOption;
    /**
     * Rating used for pricing
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ratings)
    protected Set<Ratings> ratings;
    /**
     * Total price
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_grandTotal)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double grandTotal;

    public void setChargeCode(ChargeCode chargeCode) {
        this.chargeCode = chargeCode;
    }

    public ChargeCode getChargeCode() {
        return chargeCode;
    }

    public void setForBookingOption(BookingOption forBookingOption) {
        this.forBookingOption = forBookingOption;
    }

    public BookingOption getForBookingOption() {
        return forBookingOption;
    }

    public void setRatings(Set<Ratings> ratings) {
        this.ratings = ratings;
    }

    public Set<Ratings> getRatings() {
        return ratings;
    }

    public void setGrandTotal(Double grandTotal) {
        this.grandTotal = grandTotal;
    }

    public Double getGrandTotal() {
        return grandTotal;
    }

}
