
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Product details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Product )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Product
    extends LogisticsObject
{

    /**
     * Reference to the Items or Pieces in which the product can be found.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_describedObjects)
    protected Set<PhysicalLogisticsObject> describedObjects;
    /**
     * Harmonized Commodity code, refer to hsType used. 6 minimum digits are expected.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hsCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement hsCode;
    /**
     * Manufacturing company details and contacts
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_manufacturer)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Organization manufacturer;
    /**
     * Charateristics of the product
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherCharacteristics)
    protected Set<Characteristic> otherCharacteristics;
    /**
     * Details about any other identifier, depending on the context of use
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherIdentifiers)
    protected Set<OtherIdentifier> otherIdentifiers;
    /**
     * Indicates the specific commodity on which the rate class code is applied
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_commodityItemNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String commodityItemNumber;
    /**
     * Natural language description if required
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_description)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String description;
    /**
     * Commodity description
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsCommodityDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsCommodityDescription;
    /**
     * If no Code provided, name of commodity
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsCommodityName)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsCommodityName;
    /**
     * Reference identifying the type of standard code to be used for the Commodity Classification (Brussels Tariff Nomenclature, EU Harmonized System Code, UN Standard International Trade Classification). Mandatory if the commodity code is more than 6 digits
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hsType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hsType;
    /**
     * Manufacturer's unique product identifier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_uniqueIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String uniqueIdentifier;

    public void setDescribedObjects(Set<PhysicalLogisticsObject> describedObjects) {
        this.describedObjects = describedObjects;
    }

    public Set<PhysicalLogisticsObject> getDescribedObjects() {
        return describedObjects;
    }

    public void setHsCode(CodeListElement hsCode) {
        this.hsCode = hsCode;
    }

    public CodeListElement getHsCode() {
        return hsCode;
    }

    public void setManufacturer(Organization manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Organization getManufacturer() {
        return manufacturer;
    }

    public void setOtherCharacteristics(Set<Characteristic> otherCharacteristics) {
        this.otherCharacteristics = otherCharacteristics;
    }

    public Set<Characteristic> getOtherCharacteristics() {
        return otherCharacteristics;
    }

    public void setOtherIdentifiers(Set<OtherIdentifier> otherIdentifiers) {
        this.otherIdentifiers = otherIdentifiers;
    }

    public Set<OtherIdentifier> getOtherIdentifiers() {
        return otherIdentifiers;
    }

    public void setCommodityItemNumber(String commodityItemNumber) {
        this.commodityItemNumber = commodityItemNumber;
    }

    public String getCommodityItemNumber() {
        return commodityItemNumber;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setHsCommodityDescription(String hsCommodityDescription) {
        this.hsCommodityDescription = hsCommodityDescription;
    }

    public String getHsCommodityDescription() {
        return hsCommodityDescription;
    }

    public void setHsCommodityName(String hsCommodityName) {
        this.hsCommodityName = hsCommodityName;
    }

    public String getHsCommodityName() {
        return hsCommodityName;
    }

    public void setHsType(String hsType) {
        this.hsType = hsType;
    }

    public String getHsType() {
        return hsType;
    }

    public void setUniqueIdentifier(String uniqueIdentifier) {
        this.uniqueIdentifier = uniqueIdentifier;
    }

    public String getUniqueIdentifier() {
        return uniqueIdentifier;
    }

}
