
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;


/**
 * Question holds one question and a link to an Answer The Question is provided by the party in charge of the template used
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Question )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Question
    extends LogisticsObject
{

    /**
     * Reference to the Answer to the Question
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_answer)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Answer answer;
    /**
     * Reference to the CheckTemplate the Question is from
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checkTemplate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CheckTemplate checkTemplate;
    /**
     * Text restrictions to the Answer
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_answerOptionsText)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String answerOptionsText;
    /**
     * Value restrictions to the answer
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_answerOptionsValue)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String answerOptionsValue;
    /**
     * Long text of the question
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_longText)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String longText;
    /**
     * Number of the Question within the template (alphanumeric)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_questionNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String questionNumber;
    /**
     * Section of the CheckTemplate this Question is part of
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_questionSection)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String questionSection;
    /**
     * Short text of the Question
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_shortText)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String shortText;

    public void setAnswer(Answer answer) {
        this.answer = answer;
    }

    public Answer getAnswer() {
        return answer;
    }

    public void setCheckTemplate(CheckTemplate checkTemplate) {
        this.checkTemplate = checkTemplate;
    }

    public CheckTemplate getCheckTemplate() {
        return checkTemplate;
    }

    public void setAnswerOptionsText(String answerOptionsText) {
        this.answerOptionsText = answerOptionsText;
    }

    public String getAnswerOptionsText() {
        return answerOptionsText;
    }

    public void setAnswerOptionsValue(String answerOptionsValue) {
        this.answerOptionsValue = answerOptionsValue;
    }

    public String getAnswerOptionsValue() {
        return answerOptionsValue;
    }

    public void setLongText(String longText) {
        this.longText = longText;
    }

    public String getLongText() {
        return longText;
    }

    public void setQuestionNumber(String questionNumber) {
        this.questionNumber = questionNumber;
    }

    public String getQuestionNumber() {
        return questionNumber;
    }

    public void setQuestionSection(String questionSection) {
        this.questionSection = questionSection;
    }

    public String getQuestionSection() {
        return questionSection;
    }

    public void setShortText(String shortText) {
        this.shortText = shortText;
    }

    public String getShortText() {
        return shortText;
    }

}
