
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Ranges details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Ranges )
@SuperBuilder
@EqualsAndHashCode
public class Ranges
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Rate class code e.g. Q. Refer to CXML Code List 1.4 Rate Class Codes
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_rateClassCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected RateClassCode rateClassCode;
    /**
     * ULD Rate information - ULD Rate Class Type
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldRateClassType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement uldRateClassType;
    /**
     * Maximum quantity
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_maximumQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double maximumQuantity;
    /**
     * Minimum quantity
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_minimumQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double minimumQuantity;
    /**
     * Specific commodity code linked to commodity
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_unitBasis)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String unitBasis;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Ranges {"+ name)+"<")+ id)+">")+"}");
    }

    public void setRateClassCode(RateClassCode rateClassCode) {
        this.rateClassCode = rateClassCode;
    }

    public RateClassCode getRateClassCode() {
        return rateClassCode;
    }

    public void setUldRateClassType(CodeListElement uldRateClassType) {
        this.uldRateClassType = uldRateClassType;
    }

    public CodeListElement getUldRateClassType() {
        return uldRateClassType;
    }

    public void setMaximumQuantity(Double maximumQuantity) {
        this.maximumQuantity = maximumQuantity;
    }

    public Double getMaximumQuantity() {
        return maximumQuantity;
    }

    public void setMinimumQuantity(Double minimumQuantity) {
        this.minimumQuantity = minimumQuantity;
    }

    public Double getMinimumQuantity() {
        return minimumQuantity;
    }

    public void setUnitBasis(String unitBasis) {
        this.unitBasis = unitBasis;
    }

    public String getUnitBasis() {
        return unitBasis;
    }

}
