
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.util.Set;


/**
 * Ratings details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Ratings )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Ratings
    extends LogisticsObject
{

    /**
     * Billing charge identifiers to be used for CASS. Refer to CargoXML Code List 1.33
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_billingChargeIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected ChargeIdentifier billingChargeIdentifier;
    /**
     * Indicates if charge is prepaid or collect (P, C)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_chargePaymentType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected PrepaidCollectIndicator chargePaymentType;
    /**
     * Charge type related to amount total as per bullet points 2/21 - data elements 24A - 3B  from AWB
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_chargeType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected ChargeIdentifier chargeType;
    /**
     * Entitlement code to define if charges are Due carrier (C) or Due agent (A). Refer to CXML Code List 1.3
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_entitlement)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected EntitlementCode entitlement;
    /**
     * Reference to the Prices based on this Ratings
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forPrices)
    protected Set<Price> forPrices;
    /**
     * Refer to CargoXML Code List 1.2 for Other Charges
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherChargeCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected OtherChargeCode otherChargeCode;
    /**
     * Reference to the ranges
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ranges)
    protected Set<Ranges> ranges;
    /**
     * IATA 3-letter city code of the rate combination point as defined in TACT
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_rcp)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement rcp;
    /**
     * Description of the charge e.g. Airfreight, fuel, etc.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_chargeDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String chargeDescription;
    /**
     * Reference to a price reference if existing (e.g. Allotment number, contract reference, etc.)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_priceReferenceId)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String priceReferenceId;
    /**
     * Specification of the price e.g. Street, Group, Spot, etc.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_priceSpecification)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String priceSpecification;
    /**
     * Quantity for the charge if applicable
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_quantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double quantity;
    /**
     * Subtotal of the charge
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_subTotal)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#double", max = 1)
    })
    protected Double subTotal;

    public void setBillingChargeIdentifier(ChargeIdentifier billingChargeIdentifier) {
        this.billingChargeIdentifier = billingChargeIdentifier;
    }

    public ChargeIdentifier getBillingChargeIdentifier() {
        return billingChargeIdentifier;
    }

    public void setChargePaymentType(PrepaidCollectIndicator chargePaymentType) {
        this.chargePaymentType = chargePaymentType;
    }

    public PrepaidCollectIndicator getChargePaymentType() {
        return chargePaymentType;
    }

    public void setChargeType(ChargeIdentifier chargeType) {
        this.chargeType = chargeType;
    }

    public ChargeIdentifier getChargeType() {
        return chargeType;
    }

    public void setEntitlement(EntitlementCode entitlement) {
        this.entitlement = entitlement;
    }

    public EntitlementCode getEntitlement() {
        return entitlement;
    }

    public void setForPrices(Set<Price> forPrices) {
        this.forPrices = forPrices;
    }

    public Set<Price> getForPrices() {
        return forPrices;
    }

    public void setOtherChargeCode(OtherChargeCode otherChargeCode) {
        this.otherChargeCode = otherChargeCode;
    }

    public OtherChargeCode getOtherChargeCode() {
        return otherChargeCode;
    }

    public void setRanges(Set<Ranges> ranges) {
        this.ranges = ranges;
    }

    public Set<Ranges> getRanges() {
        return ranges;
    }

    public void setRcp(CodeListElement rcp) {
        this.rcp = rcp;
    }

    public CodeListElement getRcp() {
        return rcp;
    }

    public void setChargeDescription(String chargeDescription) {
        this.chargeDescription = chargeDescription;
    }

    public String getChargeDescription() {
        return chargeDescription;
    }

    public void setPriceReferenceId(String priceReferenceId) {
        this.priceReferenceId = priceReferenceId;
    }

    public String getPriceReferenceId() {
        return priceReferenceId;
    }

    public void setPriceSpecification(String priceSpecification) {
        this.priceSpecification = priceSpecification;
    }

    public String getPriceSpecification() {
        return priceSpecification;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }

    public Double getSubTotal() {
        return subTotal;
    }

}
