
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.Set;


/**
 * Regulated Entity
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_RegulatedEntity )
@SuperBuilder
@EqualsAndHashCode
public class RegulatedEntity
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Reference to the Organization for which the RegulatedEntity information is valid
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_owningOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Organization owningOrganization;
    /**
     * Category code of the Regulated Entity
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_regulatedEntityCategory)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected RegulatedEntityCategoryCode regulatedEntityCategory;
    /**
     * Expiry date 4 digits month/year
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_regulatedEntityExpiryDate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime regulatedEntityExpiryDate;
    /**
     * Regulated entity identifier as per IATA e-CSD/CSD Resolution 65
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_regulatedEntityIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String regulatedEntityIdentifier;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("RegulatedEntity {"+ name)+"<")+ id)+">")+"}");
    }

    public void setOwningOrganization(Organization owningOrganization) {
        this.owningOrganization = owningOrganization;
    }

    public Organization getOwningOrganization() {
        return owningOrganization;
    }

    public void setRegulatedEntityCategory(RegulatedEntityCategoryCode regulatedEntityCategory) {
        this.regulatedEntityCategory = regulatedEntityCategory;
    }

    public RegulatedEntityCategoryCode getRegulatedEntityCategory() {
        return regulatedEntityCategory;
    }

    public void setRegulatedEntityExpiryDate(OffsetDateTime regulatedEntityExpiryDate) {
        this.regulatedEntityExpiryDate = regulatedEntityExpiryDate;
    }

    public OffsetDateTime getRegulatedEntityExpiryDate() {
        return regulatedEntityExpiryDate;
    }

    public void setRegulatedEntityIdentifier(String regulatedEntityIdentifier) {
        this.regulatedEntityIdentifier = regulatedEntityIdentifier;
    }

    public String getRegulatedEntityIdentifier() {
        return regulatedEntityIdentifier;
    }

}
