
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Sensor details and measurements, linked to Connected Devices
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Sensor )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Sensor
    extends PhysicalLogisticsObject
    implements Serializable
{

    /**
     * Reference to the Measurements recorded by the Sensor
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_measurements)
    protected Set<Measurement> measurements;
    /**
     * Reference to the IoT Device to which the sensor is linked
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_partOfIotDevice)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected IotDevice partOfIotDevice;
    /**
     * Type of sensor as described in Interactive Cargo Recommended Practice
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_sensorType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected SensorType sensorType;
    /**
     * Natural language description if required
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_description)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String description;
    /**
     * Human-understandable name of object depending on the context
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_name)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String name;
    /**
     * Serial number that allows to uniquely identify the object
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_serialNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String serialNumber;

    public void setMeasurements(Set<Measurement> measurements) {
        this.measurements = measurements;
    }

    public Set<Measurement> getMeasurements() {
        return measurements;
    }

    public void setPartOfIotDevice(IotDevice partOfIotDevice) {
        this.partOfIotDevice = partOfIotDevice;
    }

    public IotDevice getPartOfIotDevice() {
        return partOfIotDevice;
    }

    public void setSensorType(SensorType sensorType) {
        this.sensorType = sensorType;
    }

    public SensorType getSensorType() {
        return sensorType;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

}
