
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Action to describe store-in or store-out
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Storing )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Storing
    extends LogisticsAction
    implements Serializable
{

    /**
     * Reference to the Objects being stored in or stored out
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_storedObjects)
    protected Set<PhysicalLogisticsObject> storedObjects;
    /**
     * Enum stating whether the StoringAction describes the store-in or the store-out
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_storingType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected StoringType storingType;
    /**
     * Short text stating the exact place of storage
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_storagePlaceIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String storagePlaceIdentifier;

    public void setStoredObjects(Set<PhysicalLogisticsObject> storedObjects) {
        this.storedObjects = storedObjects;
    }

    public Set<PhysicalLogisticsObject> getStoredObjects() {
        return storedObjects;
    }

    public void setStoringType(StoringType storingType) {
        this.storingType = storingType;
    }

    public StoringType getStoringType() {
        return storingType;
    }

    public void setStoragePlaceIdentifier(String storagePlaceIdentifier) {
        this.storagePlaceIdentifier = storagePlaceIdentifier;
    }

    public String getStoragePlaceIdentifier() {
        return storagePlaceIdentifier;
    }

}
