
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * TemperatureInstructions details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TemperatureInstructions )
@SuperBuilder
@EqualsAndHashCode
public class TemperatureInstructions
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Maximum temperature of the range
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_maxTemperature)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value maxTemperature;
    /**
     * Minimum temperature of the range
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_minTemperature)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value minTemperature;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("TemperatureInstructions {"+ name)+"<")+ id)+">")+"}");
    }

    public void setMaxTemperature(Value maxTemperature) {
        this.maxTemperature = maxTemperature;
    }

    public Value getMaxTemperature() {
        return maxTemperature;
    }

    public void setMinTemperature(Value minTemperature) {
        this.minTemperature = minTemperature;
    }

    public Value getMinTemperature() {
        return minTemperature;
    }

}
