
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.time.OffsetDateTime;


/**
 * TransportLegs details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TransportLegs )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class TransportLegs
    extends LogisticsObject
{

    /**
     * Reference to the arrival Location
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_arrivalLocation)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Location arrivalLocation;
    /**
     * References to CO2Emissions
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_co2Emissions)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CO2Emissions co2Emissions;
    /**
     * Reference to the depature Location
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_departureLocation)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Location departureLocation;
    /**
     * Type of transport means service, e.g. Aircraftor Truck
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportMeansServiceType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected TransportMeansServiceType transportMeansServiceType;
    /**
     * Type of transport means, e.g. 744, RFS
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportMeansType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement transportMeansType;
    /**
     * Arrival date and time of the leg
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_arrivalDate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime arrivalDate;
    /**
     * Departure date and time of the leg
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_departureDate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime departureDate;
    /**
     * Leg number
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_legNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer legNumber;
    /**
     * Airline flight number, or rail/truck/maritime line id
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_transportIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String transportIdentifier;

    public void setArrivalLocation(Location arrivalLocation) {
        this.arrivalLocation = arrivalLocation;
    }

    public Location getArrivalLocation() {
        return arrivalLocation;
    }

    public void setCo2Emissions(CO2Emissions co2Emissions) {
        this.co2Emissions = co2Emissions;
    }

    public CO2Emissions getCo2Emissions() {
        return co2Emissions;
    }

    public void setDepartureLocation(Location departureLocation) {
        this.departureLocation = departureLocation;
    }

    public Location getDepartureLocation() {
        return departureLocation;
    }

    public void setTransportMeansServiceType(TransportMeansServiceType transportMeansServiceType) {
        this.transportMeansServiceType = transportMeansServiceType;
    }

    public TransportMeansServiceType getTransportMeansServiceType() {
        return transportMeansServiceType;
    }

    public void setTransportMeansType(CodeListElement transportMeansType) {
        this.transportMeansType = transportMeansType;
    }

    public CodeListElement getTransportMeansType() {
        return transportMeansType;
    }

    public void setArrivalDate(OffsetDateTime arrivalDate) {
        this.arrivalDate = arrivalDate;
    }

    public OffsetDateTime getArrivalDate() {
        return arrivalDate;
    }

    public void setDepartureDate(OffsetDateTime departureDate) {
        this.departureDate = departureDate;
    }

    public OffsetDateTime getDepartureDate() {
        return departureDate;
    }

    public void setLegNumber(Integer legNumber) {
        this.legNumber = legNumber;
    }

    public Integer getLegNumber() {
        return legNumber;
    }

    public void setTransportIdentifier(String transportIdentifier) {
        this.transportIdentifier = transportIdentifier;
    }

    public String getTransportIdentifier() {
        return transportIdentifier;
    }

}
