
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;


/**
 * Transport means details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_TransportMeans )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class TransportMeans
    extends PhysicalLogisticsObject
    implements Serializable
{

    /**
     * Transport Movement on which the Transport Means is used
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_operatedTransportMovement)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected TransportMovement operatedTransportMovement;
    /**
     * Company operating the transport means
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_transportOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Organization transportOrganization;
    /**
     * Required for some CO2 calculations
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_typicalCo2Coefficient)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value typicalCo2Coefficient;
    /**
     * Typical fuel comsumption (e.g. 2 L / 1 nm)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_typicalFuelConsumption)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value typicalFuelConsumption;
    /**
     * Vehicle or container type. Refer UNECE28, e.g. 4.. - Aircraft, type unknown.For Air refer to IATA Standard Schedules Information Manua in section ATA/IATA Aircraft Types
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_vehicleType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement vehicleType;
    /**
     * Model or make of the vehicle (e.g. A33-3)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_vehicleModel)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String vehicleModel;
    /**
     * Vehicle identification - e.g. aircraft registration number
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_vehicleRegistration)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String vehicleRegistration;
    /**
     * Size of the vehicle - free text
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_vehicleSize)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String vehicleSize;

    public void setOperatedTransportMovement(TransportMovement operatedTransportMovement) {
        this.operatedTransportMovement = operatedTransportMovement;
    }

    public TransportMovement getOperatedTransportMovement() {
        return operatedTransportMovement;
    }

    public void setTransportOrganization(Organization transportOrganization) {
        this.transportOrganization = transportOrganization;
    }

    public Organization getTransportOrganization() {
        return transportOrganization;
    }

    public void setTypicalCo2Coefficient(Value typicalCo2Coefficient) {
        this.typicalCo2Coefficient = typicalCo2Coefficient;
    }

    public Value getTypicalCo2Coefficient() {
        return typicalCo2Coefficient;
    }

    public void setTypicalFuelConsumption(Value typicalFuelConsumption) {
        this.typicalFuelConsumption = typicalFuelConsumption;
    }

    public Value getTypicalFuelConsumption() {
        return typicalFuelConsumption;
    }

    public void setVehicleType(CodeListElement vehicleType) {
        this.vehicleType = vehicleType;
    }

    public CodeListElement getVehicleType() {
        return vehicleType;
    }

    public void setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel;
    }

    public String getVehicleModel() {
        return vehicleModel;
    }

    public void setVehicleRegistration(String vehicleRegistration) {
        this.vehicleRegistration = vehicleRegistration;
    }

    public String getVehicleRegistration() {
        return vehicleRegistration;
    }

    public void setVehicleSize(String vehicleSize) {
        this.vehicleSize = vehicleSize;
    }

    public String getVehicleSize() {
        return vehicleSize;
    }

}
