
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;


/**
 * ULDSpecificPiece details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ULDSpecificPiece )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class ULDSpecificPiece
    extends PieceGroup
    implements Serializable
{

    /**
     * Contour code as per IATA ULD Regulation
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldContourCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement uldContourCode;
    /**
     * Type of ULD as per IATA ULD Regulation
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement uldType;
    /**
     * Shipper's Load And Count  ( total contained piece count as provided by shipper)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_slac)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer slac;
    /**
     * Serial number that allows to uniquely identify the ULD
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_uldSerialNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String uldSerialNumber;

    public void setUldContourCode(CodeListElement uldContourCode) {
        this.uldContourCode = uldContourCode;
    }

    public CodeListElement getUldContourCode() {
        return uldContourCode;
    }

    public void setUldType(CodeListElement uldType) {
        this.uldType = uldType;
    }

    public CodeListElement getUldType() {
        return uldType;
    }

    public void setSlac(Integer slac) {
        this.slac = slac;
    }

    public Integer getSlac() {
        return slac;
    }

    public void setUldSerialNumber(String uldSerialNumber) {
        this.uldSerialNumber = uldSerialNumber;
    }

    public String getUldSerialNumber() {
        return uldSerialNumber;
    }

}
