
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Set;


/**
 * Activity to describe composition and decomposition of LoadingUnits
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_UnitComposition )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class UnitComposition
    extends LogisticsActivity
    implements Serializable
{

    /**
     * References to all CompositionActions performed for the UnitComposition
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_compositionActions)
    protected Set<Composing> compositionActions;
    /**
     * Reference to the LoadingUnit composed in the Unit Composition or referenced in Composing actions
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_loadingUnit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected LoadingUnit loadingUnit;
    /**
     * Short text holding the process number if necessary
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_compositionIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String compositionIdentifier;
    /**
     * Shipper's Load And Count  ( total contained piece count as provided by shipper)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_slac)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer slac;

    public void setCompositionActions(Set<Composing> compositionActions) {
        this.compositionActions = compositionActions;
    }

    public Set<Composing> getCompositionActions() {
        return compositionActions;
    }

    public void setLoadingUnit(LoadingUnit loadingUnit) {
        this.loadingUnit = loadingUnit;
    }

    public LoadingUnit getLoadingUnit() {
        return loadingUnit;
    }

    public void setCompositionIdentifier(String compositionIdentifier) {
        this.compositionIdentifier = compositionIdentifier;
    }

    public String getCompositionIdentifier() {
        return compositionIdentifier;
    }

    public void setSlac(Integer slac) {
        this.slac = slac;
    }

    public Integer getSlac() {
        return slac;
    }

}
