
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;


/**
 * VolumePieceGroup details
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri =Vocabulary.s_c_VolumePieceGroup )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class VolumePieceGroup
    extends PieceGroup
    implements Serializable
{

    /**
     * Total volume fo the volume piece group
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_totalVolume)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value totalVolume;
    /**
     * Stackable indicator for the pieces (boolean)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_stackable)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean stackable;

    public void setTotalVolume(Value totalVolume) {
        this.totalVolume = totalVolume;
    }

    public Value getTotalVolume() {
        return totalVolume;
    }

    public void setStackable(Boolean stackable) {
        this.stackable = stackable;
    }

    public Boolean getStackable() {
        return stackable;
    }

}
