
package org.iata.onerecord.cargo.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.cargo.Vocabulary;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Information from AWB Rate Description section as per bullet point 18 - data elements 22A - 22Z from AWB
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_WaybillLineItem )
@SuperBuilder
@EqualsAndHashCode
public class WaybillLineItem
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Chargeable weight for which the rate description details apply
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_chargeableWeightForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value chargeableWeightForRate;
    /**
     * Information about the Dimensions used for the rate descbribed by the Line Item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_dimensionsForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Dimensions dimensionsForRate;
    /**
     * Gross weight for which the rate description details apply
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_grossWeightForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value grossWeightForRate;
    /**
     * Harmonized Commodity code, refer to hsType used. 6 minimum digits are expected.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hsCodeForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement hsCodeForRate;
    /**
     * Production country for the rate described by this Line Item. Refer ISO 3166-2
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_productionCountryForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement productionCountryForRate;
    /**
     * TACT Rate for rate description details
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_rateCharge)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CurrencyValue rateCharge;
    /**
     * Rate class code e.g. Q. Refer to CXML Code List 1.4 Rate Class Codes
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_rateClassCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected RateClassCode rateClassCode;
    /**
     * Rate Surcharge/Reduction - Basic Rate Class Code
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_rateClassCodeBasic)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BasicRateClassCode rateClassCodeBasic;
    /**
     * Rate Surcharge/Reduction - Percebtage of  red. / surcharge
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_ratePercentage)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value ratePercentage;
    /**
     * IATA 3-letter city code of the rate combination point as defined in TACT
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_rcp)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement rcp;
    /**
     * Information about the ULD owner code described in a ULD specific piece or used for a rate in a Line Item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldOwnerCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement uldOwnerCode;
    /**
     * ULD Rate information - ULD Rate Class Type
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldRateClassType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement uldRateClassType;
    /**
     * Information about the ULD tare weight used for the rate descbribed by the Line Item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldTareWeightForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value uldTareWeightForRate;
    /**
     * Type of ULD as per IATA ULD Regulation
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_uldType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CodeListElement uldType;
    /**
     * Volumetric weight used for the rate described by this line item
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_volumetricWeightForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected VolumetricWeight volumetricWeightForRate;
    /**
     * commodityItemNumberForRate
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_commodityItemNumberForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String commodityItemNumberForRate;
    /**
     * Goods description used in the rate described by the Line Item
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_goodsDescriptionForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String goodsDescriptionForRate;
    /**
     * Number of the line item
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_lineItemNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer lineItemNumber;
    /**
     * Number of pieces for which the rate description details apply
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_pieceCountForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer pieceCountForRate;
    /**
     * Slac used for the rate described by the Line item
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_slacForRate)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer slacForRate;
    /**
     * Serial number that allows to uniquely identify the ULD
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_uldSerialNumber)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String uldSerialNumber;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("WaybillLineItem {"+ name)+"<")+ id)+">")+"}");
    }

    public void setChargeableWeightForRate(Value chargeableWeightForRate) {
        this.chargeableWeightForRate = chargeableWeightForRate;
    }

    public Value getChargeableWeightForRate() {
        return chargeableWeightForRate;
    }

    public void setDimensionsForRate(Dimensions dimensionsForRate) {
        this.dimensionsForRate = dimensionsForRate;
    }

    public Dimensions getDimensionsForRate() {
        return dimensionsForRate;
    }

    public void setGrossWeightForRate(Value grossWeightForRate) {
        this.grossWeightForRate = grossWeightForRate;
    }

    public Value getGrossWeightForRate() {
        return grossWeightForRate;
    }

    public void setHsCodeForRate(CodeListElement hsCodeForRate) {
        this.hsCodeForRate = hsCodeForRate;
    }

    public CodeListElement getHsCodeForRate() {
        return hsCodeForRate;
    }

    public void setProductionCountryForRate(CodeListElement productionCountryForRate) {
        this.productionCountryForRate = productionCountryForRate;
    }

    public CodeListElement getProductionCountryForRate() {
        return productionCountryForRate;
    }

    public void setRateCharge(CurrencyValue rateCharge) {
        this.rateCharge = rateCharge;
    }

    public CurrencyValue getRateCharge() {
        return rateCharge;
    }

    public void setRateClassCode(RateClassCode rateClassCode) {
        this.rateClassCode = rateClassCode;
    }

    public RateClassCode getRateClassCode() {
        return rateClassCode;
    }

    public void setRateClassCodeBasic(BasicRateClassCode rateClassCodeBasic) {
        this.rateClassCodeBasic = rateClassCodeBasic;
    }

    public BasicRateClassCode getRateClassCodeBasic() {
        return rateClassCodeBasic;
    }

    public void setRatePercentage(Value ratePercentage) {
        this.ratePercentage = ratePercentage;
    }

    public Value getRatePercentage() {
        return ratePercentage;
    }

    public void setRcp(CodeListElement rcp) {
        this.rcp = rcp;
    }

    public CodeListElement getRcp() {
        return rcp;
    }

    public void setUldOwnerCode(CodeListElement uldOwnerCode) {
        this.uldOwnerCode = uldOwnerCode;
    }

    public CodeListElement getUldOwnerCode() {
        return uldOwnerCode;
    }

    public void setUldRateClassType(CodeListElement uldRateClassType) {
        this.uldRateClassType = uldRateClassType;
    }

    public CodeListElement getUldRateClassType() {
        return uldRateClassType;
    }

    public void setUldTareWeightForRate(Value uldTareWeightForRate) {
        this.uldTareWeightForRate = uldTareWeightForRate;
    }

    public Value getUldTareWeightForRate() {
        return uldTareWeightForRate;
    }

    public void setUldType(CodeListElement uldType) {
        this.uldType = uldType;
    }

    public CodeListElement getUldType() {
        return uldType;
    }

    public void setVolumetricWeightForRate(VolumetricWeight volumetricWeightForRate) {
        this.volumetricWeightForRate = volumetricWeightForRate;
    }

    public VolumetricWeight getVolumetricWeightForRate() {
        return volumetricWeightForRate;
    }

    public void setCommodityItemNumberForRate(String commodityItemNumberForRate) {
        this.commodityItemNumberForRate = commodityItemNumberForRate;
    }

    public String getCommodityItemNumberForRate() {
        return commodityItemNumberForRate;
    }

    public void setGoodsDescriptionForRate(String goodsDescriptionForRate) {
        this.goodsDescriptionForRate = goodsDescriptionForRate;
    }

    public String getGoodsDescriptionForRate() {
        return goodsDescriptionForRate;
    }

    public void setLineItemNumber(Integer lineItemNumber) {
        this.lineItemNumber = lineItemNumber;
    }

    public Integer getLineItemNumber() {
        return lineItemNumber;
    }

    public void setPieceCountForRate(Integer pieceCountForRate) {
        this.pieceCountForRate = pieceCountForRate;
    }

    public Integer getPieceCountForRate() {
        return pieceCountForRate;
    }

    public void setSlacForRate(Integer slacForRate) {
        this.slacForRate = slacForRate;
    }

    public Integer getSlacForRate() {
        return slacForRate;
    }

    public void setUldSerialNumber(String uldSerialNumber) {
        this.uldSerialNumber = uldSerialNumber;
    }

    public String getUldSerialNumber() {
        return uldSerialNumber;
    }

}
