
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;
import org.iata.onerecord.cargo.model.LogisticsAgent;
import org.iata.onerecord.cargo.model.LogisticsObject;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Access permissions granted to a logistics agent for a logistics object
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_AccessPermissions )
@SuperBuilder
@EqualsAndHashCode
public class AccessPermissions
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_hasLogisticsAgent)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_LogisticsAgent, min = 1, max = 1)
    })
    protected LogisticsAgent hasLogisticsAgent;
    /**
     * A reference to a cargo:LogisticsObject.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasLogisticsObject)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_LogisticsObject, min = 1, max = 1)
    })
    protected LogisticsObject hasLogisticsObject;
    @OWLObjectProperty(iri = Vocabulary.s_p_hasPermission)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Permission, min = 1, max = -1)
    })
    protected Set<Permission> hasPermission;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("AccessPermissions {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasLogisticsAgent(LogisticsAgent hasLogisticsAgent) {
        this.hasLogisticsAgent = hasLogisticsAgent;
    }

    public LogisticsAgent getHasLogisticsAgent() {
        return hasLogisticsAgent;
    }

    public void setHasLogisticsObject(LogisticsObject hasLogisticsObject) {
        this.hasLogisticsObject = hasLogisticsObject;
    }

    public LogisticsObject getHasLogisticsObject() {
        return hasLogisticsObject;
    }

    public void setHasPermission(Set<Permission> hasPermission) {
        this.hasPermission = hasPermission;
    }

    public Set<Permission> getHasPermission() {
        return hasPermission;
    }

}
