
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;
import org.iata.onerecord.cargo.model.Organization;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.Set;


/**
 * Superclass for all kinds of requests (i.e someone requsted something (e.g. subscription, access, etc.) at a publisher/holder of a logistics object)
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ActionRequest )
@SuperBuilder
@EqualsAndHashCode
public class ActionRequest
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Error object(s) if the processing was not successful
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasError)
    protected Set<Error> hasError;
    /**
     * has Request Status
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasRequestStatus)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_RequestStatus, min = 1, max = 1)
    })
    protected RequestStatus hasRequestStatus;
    /**
     * Organization Identifier that represents the Organization that has requested the action
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_isRequestedBy)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Organization, min = 1, max = 1)
    })
    protected Organization isRequestedBy;
    @OWLObjectProperty(iri = Vocabulary.s_p_isRevokedBy)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Organization, max = 1)
    })
    protected Organization isRevokedBy;
    /**
     * Datetime when the request was created
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_isRequestedAt)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", min = 1, max = 1)
    })
    protected OffsetDateTime isRequestedAt;
    /**
     * The datetime when the action request was revoked.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_isRevokedAt)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#dateTime", max = 1)
    })
    protected OffsetDateTime isRevokedAt;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("ActionRequest {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasError(Set<Error> hasError) {
        this.hasError = hasError;
    }

    public Set<Error> getHasError() {
        return hasError;
    }

    public void setHasRequestStatus(RequestStatus hasRequestStatus) {
        this.hasRequestStatus = hasRequestStatus;
    }

    public RequestStatus getHasRequestStatus() {
        return hasRequestStatus;
    }

    public void setIsRequestedBy(Organization isRequestedBy) {
        this.isRequestedBy = isRequestedBy;
    }

    public Organization getIsRequestedBy() {
        return isRequestedBy;
    }

    public void setIsRevokedBy(Organization isRevokedBy) {
        this.isRevokedBy = isRevokedBy;
    }

    public Organization getIsRevokedBy() {
        return isRevokedBy;
    }

    public void setIsRequestedAt(OffsetDateTime isRequestedAt) {
        this.isRequestedAt = isRequestedAt;
    }

    public OffsetDateTime getIsRequestedAt() {
        return isRequestedAt;
    }

    public void setIsRevokedAt(OffsetDateTime isRevokedAt) {
        this.isRevokedAt = isRevokedAt;
    }

    public OffsetDateTime getIsRevokedAt() {
        return isRevokedAt;
    }

}
