
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;
import org.iata.onerecord.cargo.model.LogisticsObject;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Change )
@SuperBuilder
@EqualsAndHashCode
public class Change
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * A reference to a cargo:LogisticsObject.
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasLogisticsObject)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_LogisticsObject, min = 1, max = 1)
    })
    protected LogisticsObject hasLogisticsObject;
    /**
     * Operation(s) to apply as PATCH on a Logistics Object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasOperation)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Operation, min = 1, max = -1)
    })
    protected Set<Operation> hasOperation;
    /**
     * Reason for the request (optional)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasDescription)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasDescription;
    /**
     * Revision number of the Logistics Object, starting with 0 for changing the initial revision of a Logistics Object
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasRevision)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#positiveInteger", min = 1, max = 1)
    })
    protected Integer hasRevision;
    /**
     * Flag specifying if the requestor wants to receive Notification from the publisher when the status of an action request changed, default=FALSE
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_notifyRequestStatusChange)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", min = 1, max = 1)
    })
    protected Boolean notifyRequestStatusChange;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Change {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasLogisticsObject(LogisticsObject hasLogisticsObject) {
        this.hasLogisticsObject = hasLogisticsObject;
    }

    public LogisticsObject getHasLogisticsObject() {
        return hasLogisticsObject;
    }

    public void setHasOperation(Set<Operation> hasOperation) {
        this.hasOperation = hasOperation;
    }

    public Set<Operation> getHasOperation() {
        return hasOperation;
    }

    public void setHasDescription(String hasDescription) {
        this.hasDescription = hasDescription;
    }

    public String getHasDescription() {
        return hasDescription;
    }

    public void setHasRevision(Integer hasRevision) {
        this.hasRevision = hasRevision;
    }

    public Integer getHasRevision() {
        return hasRevision;
    }

    public void setNotifyRequestStatusChange(Boolean notifyRequestStatusChange) {
        this.notifyRequestStatusChange = notifyRequestStatusChange;
    }

    public Boolean getNotifyRequestStatusChange() {
        return notifyRequestStatusChange;
    }

}
