
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;

import java.io.Serializable;


/**
 * Change Request containing updates on a Logistics Object
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ChangeRequest )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class ChangeRequest
    extends ActionRequest
    implements Serializable
{

    /**
     * Contains submitted Change object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasChange)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Change, min = 1, max = 1)
    })
    protected Change hasChange;

    public void setHasChange(Change hasChange) {
        this.hasChange = hasChange;
    }

    public Change getHasChange() {
        return hasChange;
    }

}
