
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;
import org.iata.onerecord.cargo.model.Thing;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;


/**
 * Used as response of endpoints returning a collection of more than one graph, i.e. more than one not linked subjects.
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Collection )
@SuperBuilder
@EqualsAndHashCode
@NoArgsConstructor
public class Collection
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Item that is contained in a collection
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_hasItem)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, min = 1, max = -1)
    })
    protected Set<Thing> hasItem;
    /**
     * The number of total items contained in a collection
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasTotalItems)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", min = 1, max = 1)
    })
    protected Integer hasTotalItems;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Collection {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasItem(Set<Thing> hasItem) {
        this.hasItem = hasItem;
    }

    public Set<Thing> getHasItem() {
        return hasItem;
    }

    public void setHasTotalItems(Integer hasTotalItems) {
        this.hasTotalItems = hasTotalItems;
    }

    public Integer getHasTotalItems() {
        return hasTotalItems;
    }

}
