
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;

import java.io.Serializable;
import java.net.URI;
import java.util.Map;
import java.util.Set;


/**
 * Error details that belong to an error
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_ErrorDetail )
@SuperBuilder
@EqualsAndHashCode
public class ErrorDetail
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Error code is a numeric or alphanumeric code that can be used to determine the source of the error and why it occured.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasCode;
    /**
     * Message that describes the error
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasMessage)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String hasMessage;
    /**
     * Property of the object for which the error applies in IRI format, i.e. https://onerecord.iata.org/ns/cargo#hasVolumetricWeight
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasProperty)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#anyURI", max = 1)
    })
    protected URI hasProperty;
    /**
     * URI of the object where the error occurred
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasResource)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#anyURI", max = 1)
    })
    protected URI hasResource;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("ErrorDetail {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasCode(String hasCode) {
        this.hasCode = hasCode;
    }

    public String getHasCode() {
        return hasCode;
    }

    public void setHasMessage(String hasMessage) {
        this.hasMessage = hasMessage;
    }

    public String getHasMessage() {
        return hasMessage;
    }

    public void setHasProperty(URI hasProperty) {
        this.hasProperty = hasProperty;
    }

    public URI getHasProperty() {
        return hasProperty;
    }

    public void setHasResource(URI hasResource) {
        this.hasResource = hasResource;
    }

    public URI getHasResource() {
        return hasResource;
    }

}
