
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;

import java.io.Serializable;
import java.net.URI;
import java.util.Map;
import java.util.Set;


/**
 * Operation Request contained in the PATCH body
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Operation )
@SuperBuilder
@EqualsAndHashCode
public class Operation
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    @OWLObjectProperty(iri = Vocabulary.s_p_o)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_OperationObject, min = 1, max = 1)
    })
    protected OperationObject o;
    @OWLObjectProperty(iri = Vocabulary.s_p_op)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_PatchOperation, min = 1, max = 1)
    })
    protected PatchOperation op;
    /**
     * Operations objects must have exactly one p, predicate, member. The value of this member must be an URI, e.g. https://onerecord.iata.org/ns/cargo#hasGoodsDescription
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_p)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#anyURI", min = 1, max = 1)
    })
    protected URI p;
    /**
     * Operation objects MUST have exactly one "s", subject, member. The value of this member MUST be one of IRI or blank node.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_s)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", min = 1, max = 1)
    })
    protected String s;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("Operation {"+ name)+"<")+ id)+">")+"}");
    }

    public void setO(OperationObject o) {
        this.o = o;
    }

    public OperationObject getO() {
        return o;
    }

    public void setOp(PatchOperation op) {
        this.op = op;
    }

    public PatchOperation getOp() {
        return op;
    }

    public void setP(URI p) {
        this.p = p;
    }

    public URI getP() {
        return p;
    }

    public void setS(String s) {
        this.s = s;
    }

    public String getS() {
        return s;
    }

}
