
package org.iata.onerecord.api.model;

import cz.cvut.kbss.jopa.model.annotations.*;
import cz.cvut.kbss.jopa.vocabulary.RDFS;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.iata.onerecord.api.Vocabulary;

import java.io.Serializable;
import java.net.URI;
import java.util.Map;
import java.util.Set;


/**
 * Object to modify in the PATCH request
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri = Vocabulary.s_c_OperationObject )
@SuperBuilder
@EqualsAndHashCode
public class OperationObject
    implements Serializable
{

    @Id(generated = true)
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * Data type of the field to update, must be a valid URI, e.g. http://www.w3.org/2001/XMLSchema#int
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasDatatype)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#anyURI", min = 1, max = 1)
    })
    protected URI hasDatatype;
    /**
     * Updated value for the field
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_hasValue)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", min = 1, max = 1)
    })
    protected String hasValue;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("OperationObject {"+ name)+"<")+ id)+">")+"}");
    }

    public void setHasDatatype(URI hasDatatype) {
        this.hasDatatype = hasDatatype;
    }

    public URI getHasDatatype() {
        return hasDatatype;
    }

    public void setHasValue(String hasValue) {
        this.hasValue = hasValue;
    }

    public String getHasValue() {
        return hasValue;
    }

}
