
package org.w3c.auth.acl.model;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;
import org.w3c.auth.acl.Vocabulary;

import java.io.Serializable;


/**
 * The class of read operations
 * 
 * This class was generated by OWL2Java 1.1.4
 * 
 */
@OWLClass(iri =Vocabulary.s_c_Read )
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
public class Read
    extends Access
    implements Serializable
{


}
